// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wttbljufhxwdhthtinns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dGJsanVmaHh3ZGh0aHRpbm5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2Njk1MTMsImV4cCI6MjA2NjI0NTUxM30.x-ey7vnK_qBMTjmO01yu_2in239oUKzT4TcVFGLJsF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);